### ISSUE TITLE
Error parsing cl.obo (from the readme)

### ISSUE THREAD

**Issue by jkanche** [althonos/pronto#123]
```
>>> cl = Ontology("http://purl.obolibrary.org/obo/cl.obo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/pangenic/lib/python3.8/site-packages/pronto/ontology.py", line 218, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "/usr/local/Caskroom/miniconda/base/envs/pangenic/lib/python3.8/site-packages/pronto/parsers/obo.py", line 46, in parse_from
    raise SyntaxError(s.args[0], location) from None
  File "http://purl.obolibrary.org/obo/cl.obo", line 31344
    xref: xref (ILX:0770149)␊
               ^
SyntaxError: expected EOL or QuotedString
```

**Comment by althonos** [comment]
Hi @jkanche ,

this is due to a syntax issue in CL. I have reported it (see related issue) and this should be fixed when they publish a new release.

**Comment by AaronNing** [comment]
Hi @althonos , Syntax Error again in parsing cl.obo. Is this external too? Thanks.
```
In [1]: import pronto

In [2]: cl = pronto.Ontology("http://purl.obolibrary.org/obo/cl.obo")
Traceback (most recent call last):

  File ~/miniconda3/envs/CL/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3398 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Input In [2] in <cell line: 1>
    cl = pronto.Ontology("http://purl.obolibrary.org/obo/cl.obo")

  File ~/.local/lib/python3.8/site-packages/pronto/ontology.py:283 in __init__
    cls(self).parse_from(_handle)  # type: ignore

  File ~/.local/lib/python3.8/site-packages/pronto/parsers/obo.py:45 in parse_from
    raise SyntaxError(s.args[0], location) from None

  File http://purl.obolibrary.org/obo/cl.obo:688
    synonym: "Acetylcholine" EXACT [KEGG COMPOUND:]␊
                                         ^
SyntaxError: expected QuotedString


In [3]: pronto.__version__
Out[3]: '2.5.0'
```

**Comment by althonos** [comment]
Hi @AaronNing, this is again an error of CL, the cross-reference part of this line is invalid.
