### ISSUE TITLE
.obo SyntaxErorrs

### ISSUE THREAD

**Issue by joelduerksen** [althonos/pronto#131]
Basically every .obo file I've tried reading errors out with a SyntaxError.   I'm seeing two types of issues, 1. obo files do not appear to be following one standard format.  

2. actual issues in the files.   How is everyone handling these challenges?  cl.obo has this at the moment, I want to be able to silently ignore these and still read the rest of the data (store a None for date is much better than failing for the entire file)
Sorry if this is a noob question, but can we force pronto to continue in the face of messy/real data?

>>> cl = Ontology("http://purl.obolibrary.org/obo/cl.obo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/plastic/anaconda3/envs/uberon/lib/python3.8/site-packages/pronto/ontology.py", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "/home/plastic/anaconda3/envs/uberon/lib/python3.8/site-packages/pronto/parsers/obo.py", line 45, in parse_from
    raise SyntaxError(s.args[0], location) from None
  File "http://purl.obolibrary.org/obo/cl.obo", line 163708
    creation_date: 202z-09-29T15:45:36Z␊
                   ^
SyntaxError: expected Iso8601Year

**Comment by althonos** [comment]
Hi @joelduerksen ,

`pronto` is backed by `fastobo`, which is a library I developed during a MSc placement in order to assess the syntactic correctness of OBO ontologies. As such, it means that `pronto` will only load *correct* ontologies, in an effort to improve the landscape of OBO products.

So, in the case of Uberon and CL, I am in contact with the ontology developers, so I can likely patch the issues. The third example you are showing is something else, because you request a non-existing file to the OBO library :smile:

**Comment by althonos** [comment]
UBERON issues have been reported in [uberon#1850](https://github.com/obophenotype/uberon/issues/1850). CL issues are actually coming from UBERON imports, so fixing UBERON will likely fix CL as well.

**Comment by jkanche** [comment]
running into the same issue as well...
