### ISSUE TITLE
OBO parsing fails with a misleading error message

### ISSUE THREAD

**Issue by mukund109** [althonos/pronto#146]
When parsing `cellosaurus.obo` downloaded from [here](https://ftp.expasy.org/databases/cellosaurus/), I get this error.

![image](https://user-images.githubusercontent.com/15649806/127514312-6d0154a2-015b-453b-b736-4fe4ef5b84a9.png)

The error is fixed when I manually remove
1. lines starting with `!` (in particular lines 27-48)
2. line with date information `date: 05:20:2021 12:00` (line 3)

**Comment by althonos** [comment]
Hi @mukund109 , three things:

- concerning the top error error message, this seems to be an IPython thing, because when I run it with the base Python shell I actually get the location of the syntax error in the OBO file: 
   ```python
   >>> import pronto
   >>> pronto.Ontology("cellosaurus.obo")
     File "<stdin>", line 3
       date: 05:20:2021 12:00␊
                ^
   SyntaxError: expected NaiveMonth

   The above exception was the direct cause of the following exception:

   Traceback (most recent call last):
     File "<stdin>", line 1, in <module> 
     File "/home/althonos/.local/lib/python3.9/site-packages/pronto/ontology.py", line 283, in __init__
       cls(self).parse_from(_handle)  # type: ignore
     File "/home/althonos/.local/lib/python3.9/site-packages/pronto/parsers/obo.py", line 18, in parse_from
       doc = fastobo.iter(handle, ordered=True)
   TypeError: expected path or binary file handle
   ```
- concerning the error type (the fact that you get a `TypeError` where you would expect the `SyntaxError` to be raised directly), this is a bug in `fastobo-py`, I'm fixing it ATM.
- concerning the `cellosaurus.obo` file, it cannot be parsed because it is not compatible with the [OBO format version 1.4](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.2.2.3), it contains many syntax errors (that `pronto` cannot ignore *by design*). If you are in conttact with the ExPasy people, you can try reporting it to them directly, otherwise I'll send them an email to see what we can do about it. Most of the issues seem to be concentrated in the Xref IDs so that shouldn't be to hard to fix.

**Comment by sunnyosun** [comment]
Hi @althonos,

I'm having a different issue when reading the recent cellosaurus obo file with `pronto 2.7.3`: https://ftp.expasy.org/databases/cellosaurus/cellosaurus.obo

<img width="840" height="497" alt="Image" src="https://github.com/user-attachments/assets/d94302fb-ed63-4303-87c1-6566ce0b7378" />

Is this also due to the formatting of `cellosaurus.obo`? I'd be happy to reach out to ExPasy if that's the case.

Thank you!
Sunny

**Comment by althonos** [comment]
Hi @sunnyosun, the OBO date should be in `dd:MM:yyyy` format as per the [1.4 specification](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.2.1). Please report to the Cellosaurus authors so they fix their OBO file!
