### ISSUE TITLE
Error when parsing MONDO

### ISSUE THREAD

**Issue by genomics-geek** [althonos/pronto#17]
I was using pronto to work with MONDO found [here](http://purl.obolibrary.org/obo/mondo.obo).  However I get this error:

```python
Traceback (most recent call last):
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/pronto/parser/obo.py", line 222, in _classify
    s = _cached_synonyms[obo_header]
KeyError: '"CFS" EXACT ABBREVIATION [https://en.wikipedia.org/wiki/Chronic_fatigue_syndrome#Naming]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/pronto/synonym.py", line 115, in __init__
    self.syn_type = SynonymType._instances[syn_type]
KeyError: 'ABBREVIATION'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/phenotype_ontologies/management/commands/sync_ontology.py", line 36, in handle
    data = Ontology(purl, timeout=10)
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/pronto/ontology.py", line 109, in __init__
    self.parse(handle, parser)
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/pronto/ontology.py", line 224, in parse
    self.meta, self.terms, self.imports = p.parse(stream)
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/pronto/parser/obo.py", line 69, in parse
    terms = cls._classify(_rawtypedef, _rawterms)
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/pronto/parser/obo.py", line 224, in _classify
    s = Synonym.from_obo(obo_header, scope)
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/pronto/synonym.py", line 138, in from_obo
    return cls(**groupdict)
  File "/Users/gonzalezma/.pyenv/versions/nexus/lib/python3.5/site-packages/pronto/synonym.py", line 118, in __init__
    raise ValueError("Undefined synonym type: {}".format(syn_type))
ValueError: Undefined synonym type: ABBREVIATION
```

**Comment by althonos** [comment]
Actually, this is an error within the Mondo ontology: they should declare the `ABBREVIATION` synonymtype (like done [here](https://github.com/sanger-pathogens/Bio-HICF-Schema/blob/master/t/data/08_broken_gaz.obo)):
```obo
synonymtypedef: ABBREVIATION "ABBREVIATION" EXACT
```

I'm not sure if declaring the synonym type is required (it seems to be in the OBO flat guide, but it's not normative, and I couldn't find that piece of information in the OBO specification), so I'm also not sure if the undefined synonym type should be silenced or not.

I created an issue in the Mondo repository. For now, the other fix is to open the `mondo.obo` and add the line above next to other typedefs, before it is fixed upstream.

**Comment by genomics-geek** [comment]
ah - that makes sense.  I figured it was something that was missing.  Thanks for looking into it.

**Comment by althonos** [comment]
Works fine with latest release.
