### ISSUE TITLE
Windows multiprocessing: AttributeError: 'Queue' object has no attribute 'size'

### ISSUE THREAD

**Issue by Tomnl** [althonos/pronto#2]
After testing mzml2isa on windows 7 the following error message is displayed from the the pronto package

Installed from pip (mzml2isa  0.4.25)

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\tnl495>mzml2isa
Process _OboClassifier-1:
Traceback (most recent call last):
  File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootst
    self.run()
  File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in
    term = self.queue.get()
  File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
    self.size.increment(-1)
AttributeError: 'Queue' object has no attribute 'size'
Process _OboClassifier-8:
Traceback (most recent call last):
  File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootst
    self.run()
  File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in
P rocess _OboClassifier-2:
   term = self.queue.get()
Traceback (most recent call last):
  File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootst
 P    self.run()
rocess _OboClassifier-4:
T raceback (most recent call last):
 File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
 File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in r
  File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootst
    term = self.queue.get()
    self.run()
      self.size.increment(-1)
 File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in r
 File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
    term = self.queue.get()
  File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
    self.size.increment(-1)
AttributeError: 'Queue' object has no attribute 'size'
AttributeError: 'Queue' object has no attribute 'size'
    self.size.increment(-1)
AttributeError: 'Queue' object has no attribute 'size'
Process _OboClassifier-6:
Traceback (most recent call last):
  File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootst
Process _OboClassifier-16:
 Traceback (most recent call last):
  File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootst
    self.run()
   self.run()
  File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in
P rocess _OboClassifier-9:
 File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in r
TPraceback (most recent call last):
rocess _OboClassifier-7:
   PT File "c:\python27\lib\multiprocessing\process.py", line 258, in _bo
   term = self.queue.get()
   term = self.queue.get()
rocess _OboClassifier-10:
   raceback (most recent call last):
PT File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
   self.run()
 File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
rocess _OboClassifier-14:
raceback (most recent call last):
   PP PT    self.size.increment(-1)
 File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstr
 File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in r
rocess _OboClassifier-5:
rocess _OboClassifier-12:
   self.size.increment(-1)
rocess _OboClassifier-11:
raceback (most recent call last):
 File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstr
A T PTPPAT ttributeError: 'Queue' object has no attribute 'size'
   self.run()
raceback (most recent call last):
   term = self.queue.get()
rocess _OboClassifier-15:
raceback (most recent call last):
rocess _OboClassifier-13:
rocess _OboClassifier-3:
ttributeError: 'Queue' object has no attribute 'size'
raceback (most recent call last):
 File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstr
    T TT     self.run()
 File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in r
 File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstr
 File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
raceback (most recent call last):
 File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstr
raceback (most recent call last):
raceback (most recent call last):
 File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstr
   self.run()
           File "c:\python27\lib\site-packages\pronto\parser\obo.py", lin
   term = self.queue.get()
 File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstr
 File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstr
   self.run()
 File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstr
   self.size.increment(-1)
   self.run()
   self.run()
 File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in r
    A     File "c:\python27\lib\site-packages\pronto\utils.py", line 257,
   term = self.queue.get()
  File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in
ttributeError: 'Queue' object has no attribute 'size'
   self.run()
   self.run()
 File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in r
 File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in r
   self.run()
    term = self.queue.get()
      File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in
   self.size.increment(-1)
    File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, i
   term = self.queue.get()
 File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in r
 File "c:\python27\lib\site-packages\pronto\parser\obo.py", line 33, in r
 File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
A   term = self.queue.get()
   term = self.queue.get()
   ttributeError: 'Queue' object has no attribute 'size'
    File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in ge
    self.size.increment(-1)
    term = self.queue.get()
   term = self.queue.get()
 File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
   term = self.queue.get()
 File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
   self.size.increment(-1)
A     AttributeError: 'Queue' object has no attribute 'size'
 File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
   self.size.increment(-1)
 File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
  File "c:\python27\lib\site-packages\pronto\utils.py", line 257, in get
   self.size.increment(-1)
ttributeError: 'Queue' object has no attribute 'size'
A   self.size.increment(-1)
   AttributeError: 'Queue' object has no attribute 'size'
A   self.size.increment(-1)
   self.size.increment(-1)
   self.size.increment(-1)
ttributeError: 'Queue' object has no attribute 'size'
ttributeError: 'Queue' object has no attribute 'size'
AAAttributeError: 'Queue' object has no attribute 'size'
ttributeError: 'Queue' object has no attribute 'size'
ttributeError: 'Queue' object has no attribute 'size'

**Comment by althonos** [comment]
This is strange, Queue.size should be SharedCounter object...

**Comment by althonos** [comment]
Hi @Tomnl, would you mind testing that with the experimental branch ? I did some slight changes and reverted to stdlib `multiprocessing.queues.Queue`, as well as changing the code a tad to avoid using `Queue.size()`... Would you mind telling me if it solves the issue ?

**Comment by Tomnl** [comment]
Yeah sure. I am away this weekend without a computer so will have to do it on Monday though.

**Comment by althonos** [comment]
Tested on Windows 8.1 x64 machine. Assumed to be fixed in v0.4.0.
