### ISSUE TITLE
Ignore errors per term when parsing

### ISSUE THREAD

**Issue by bkille** [althonos/pronto#57]
I am trying to parse the GO database:
```
format-version: 1.2
data-version: releases/2020-01-01
```

However, when I read the file via:
```Python
from pronto import Ontology
GO = Ontology("/home/dbs/GO_new/go-basic.obo")

Traceback (most recent call last):

  File "/scratch0/software/miniconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-0166872dad99>", line 1, in <module>
    GO = Ontology("/home/dbs/GO_new/go-basic.obo")

  File "/scratch0/software/miniconda3/lib/python3.7/site-packages/pronto/ontology.py", line 174, in __init__
    self._build_subclassing_cache()

  File "/scratch0/software/miniconda3/lib/python3.7/site-packages/contexter.py", line 96, in __exit__
    reraise(exc)

  File "/scratch0/software/miniconda3/lib/python3.7/site-packages/contexter.py", line 26, in reraise
    raise exc[1].with_traceback(exc[2])

  File "/scratch0/software/miniconda3/lib/python3.7/site-packages/pronto/ontology.py", line 167, in __init__
    cls(self).parse_from(_handle)

  File "/scratch0/software/miniconda3/lib/python3.7/site-packages/pronto/parsers/obo.py", line 36, in parse_from
    raise SyntaxError(s.args[0], location) from None

  File "/home/dbs/GO_new/go-basic.obo", line 284367
    def: "Catalysis of the reaction: (6S)-6-hydroxyhyoscyamine + 2-oxoglutarate + O(2) = CO(2) + H(2)O + H(+) + scopolamine + succinate." [EC: 1.14.20.13, RHEA:12797]
                                                                                                                                               ^
SyntaxError: expected QuotedString
```

**Comment by althonos** [comment]
Hi @bkille, this is actually an error from GO that was reported here: https://github.com/geneontology/go-ontology/issues/18701

I'm not sure it would be possible to ignore errors per term as this could lead to a semantic change in the obtained `Ontology` object; plus I don't think the parser would be able to do that without massive changes on my part.
